### ISSUE TITLE
Please support vitest 2x

### ISSUE THREAD

**Issue by rkhaslarov** [raegen/vite-plugin-vitest-cache#8]
Please support vitest 2x

**Comment by raegen** [comment]
> Please support vitest 2x
It should support vitest 2x. What issues have you encountered?

**Comment by raegen** [comment]
Based on the silence, I assume everything's in order now (it should be, since I've been using it myself with vitest ^2 for a while now), so I'm closing this to cleanup. Please feel free to reach out if you encounter any issues.

**Comment by raegen** [comment]
Based on the silence, I assume everything's in order now (it should be, since I've been using it myself with vitest ^2 for a while now), so I'm closing this to cleanup. Please feel free to reach out if you encounter any issues.

**Comment by honzahruby** [comment]
@raegen I don’t know what was the issue here, but at least vitest v3 for sure doesn’t support `getTestFilepaths` so the whole plugin crashes at the start
